/*
Given two strings s and t which consist of only lowercase letters.
String t is generated by random shuffling string s and then add one more letter at a random position.
Find the letter that was added in t.

Example:
Input:
s = "abcd"
t = "abcde"

Output: e
Explanation: 'e' is the letter that was added.
*/

// Solution 1: use std::unordered_map
char findTheDifference(std::string s, std::string t)
{
    std::unordered_map<char, int> M;
    for (int i = 0, iEnd = (int)s.size(); i < iEnd; ++i)
    {
        auto it = M.find(s[i]);
        if (it != M.end())
            it->second++;
        else
            M[s[i]] = 1;
    }
    
    int j = 0;
    for (int jEnd = (int)t.size(); j < jEnd; ++j)
    {
        auto it = M.find(t[j]);
        if (it != M.end())
        {
            if (it->second == 0) break;
            it->second--;
        }
        else
        {
            break;
        }
    }
    return t[j];
}

// Solution 2:
char findTheDifference(std::string s, std::string t) {
    std::vector<int> count(26);
    for (const auto& ch : s) {
        count[ch-'a']++;
    }

    char diff = '0';
    for (const auto& ch : t) {
        count[ch-'a']--;
        if (count[ch-'a'] < 0)
            diff = ch;
    }
    return diff;
}
